# -*- coding: utf-8 -*-
"""BlenderBot  (AI Chat Bot)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WF4MedXjq5ZPEjBjQzo8O9AvaTRI7ENN
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
model_name = "facebook/blenderbot-400M-distill"
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

conversation_history = []

def chat(message, history):
    conversation_history.append(message)
    history_string = "\n".join(conversation_history)

    inputs = tokenizer(history_string, return_tensors="pt")

    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        temperature=0.7,
        do_sample=True
    )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    conversation_history.append(response)

    return response


iface = gr.ChatInterface(
    fn=chat,
    title="BlenderBot Chatbot",
    description="Chatbot powered by facebook/blenderbot-400M-distill"
)

iface.launch()